global:
  scrape_interval: 15s


scrape_configs:
  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service:3100']

  - job_name: 'task-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['task-service:3004']

  - job_name: 'board-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['board-service:3005']


rule_files:
  - 'alert.rules.yml'

